// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyxON04VOWd75Q1jiTYs6eUtAOHHu7c3I',
    appId: '1:1006593079752:web:147e0c59e064e42b46a8fd',
    messagingSenderId: '1006593079752',
    projectId: 'coba1-66f35',
    authDomain: 'coba1-66f35.firebaseapp.com',
    storageBucket: 'coba1-66f35.firebasestorage.app',
    measurementId: 'G-47KVVE3WE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADFwyKiUAr26wsl3LJub1PHTUteE0kO6c',
    appId: '1:1006593079752:android:ddf9c3510d992a0046a8fd',
    messagingSenderId: '1006593079752',
    projectId: 'coba1-66f35',
    storageBucket: 'coba1-66f35.firebasestorage.app',
  );

}